# this Makefile simply wraps the compile tool acgmake

# compile debug version
dbg:
	../acgmake/bin/acgmake -j

# remove debug version
clean:
	../acgmake/bin/acgmake clean

# compile optimized version
max:
	../acgmake/bin/acgmake -j -max

# remove optimized version
maxclean:
	../acgmake/bin/acgmake -max clean
